project:
  type: manuscript
  output-dir: _manuscript

manuscript:
  article: index.qmd

format:
  docx:
    toc: false
    notebook-links: false
    number-sections: true
    fig-width: 7
    fig-height: 3.5
    fig-dpi: 300

execute:
  echo: false
  warning: false
  message: false
